import { Manrope, Inter_Tight, Inter } from "next/font/google";
import "./globals.css";


const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "manrope",
});

export const metadata = {
  title: "Hyoteki | Improve your Japanese skills",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${interTight.className} antialiased overflow-hidden h-dvh w-full bg-[#191919] text-[#B7B7B7]`}>
        {children}
      </body>
    </html>
  );
}
